In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import svm, tree
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.linear_model import LogisticRegression
import xgboost
from sklearn.model_selection import train_test_split

In [2]:
df_train = pd.read_csv('train.csv')
# df_test = pd.read_csv('test.csv')

In [3]:
df_train

LABEL   FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6   FLUX.7  \
0         1   198.78   211.28   187.27   202.34   211.43   208.74   230.06   
1         1    16.53    11.54    14.44    13.30    11.29     5.35    14.00   
2         1    -9.64    -8.82   -11.90    -9.24    -7.26    -6.44    -2.58   
3         1   -18.31     4.13    76.75     9.38    -9.81     5.44   -63.56   
4         1   245.06   177.37   174.62    47.12    33.50  -103.66  -127.13   
...     ...      ...      ...      ...      ...      ...      ...      ...   
4803      1     6.45     3.95    -3.72     5.16    14.89    19.36     6.13   
4804      1   210.50   162.72   148.73   144.62   150.96    70.64    55.06   
4805      1  1373.12  1460.25  1543.87  1585.65  1689.44  1775.72  1845.50   
4806      1    30.01    42.47    25.59    27.33    38.41    26.70    24.14   
4807      1  -591.74  -571.56  -580.32  -522.65  -496.57  -293.84   -95.74   

       FLUX.8   FLUX.9  ...  FLUX.3188  FLUX.3189  FLUX.3190  FLUX.3191  \
0      175.02   175.70  ...     131.66     143.17     190.08     138.63   
1        8.70    11.14  ...       7.54       7.43      -2.09      14.06   
2       -2.18    -3.13  ...      18.89      18.15      20.51      13.78   
3       27.00   -65.00  ...      57.00      41.69      75.75      99.63   
4     -153.78  -211.56  ...    1015.00    1054.44     975.03    1009.53   
...       ...      ...  ...        ...        ...        ...        ...   
4803    19.24     3.45  ...      -9.28      37.19      35.75      63.11   
4804    70.12    67.70  ...     -21.68     -78.74    -142.32    -176.99   
4805  1952.56  2052.97  ...    -656.03    -607.41    -476.91    -375.69   
4806    16.66    23.63  ...      24.51      34.49      24.45      14.93   
4807  -430.12  -466.17  ...      60.95      21.38      28.43      -3.49   

      FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0        148.90     151.77      83.11      84.24     105.44     117.55  
1          3.41      12.41     -12.72       4.81      -2.87       2.59  
2         20.28      20.91      -7.91      -1.59      -2.48      -3.20  
3         59.88      71.57      -0.69      86.07     171.57      75.00  
4       1016.22    1065.31    1014.09    1022.56    1043.37    1075.69  
...         ...        ...        ...        ...        ...        ...  
4803      30.55      42.53      63.00      90.28      64.55      74.83  
4804    -224.43    -282.02    -315.21    -308.97    -238.11    -188.83  
4805    -274.31     -99.66   -2032.16   -1924.44   -1874.25   -1796.19  
4806      10.78      25.11       9.15      29.58      27.07      19.05  
4807     -20.14     -50.59     -69.67     -53.18     -69.59     -53.81  

[4808 rows x 3198 columns]

In [4]:
df_train['LABEL'] = df_train['LABEL'].apply(lambda x: 0 if x==1 else 1)
df_train

LABEL   FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6   FLUX.7  \
0         0   198.78   211.28   187.27   202.34   211.43   208.74   230.06   
1         0    16.53    11.54    14.44    13.30    11.29     5.35    14.00   
2         0    -9.64    -8.82   -11.90    -9.24    -7.26    -6.44    -2.58   
3         0   -18.31     4.13    76.75     9.38    -9.81     5.44   -63.56   
4         0   245.06   177.37   174.62    47.12    33.50  -103.66  -127.13   
...     ...      ...      ...      ...      ...      ...      ...      ...   
4803      0     6.45     3.95    -3.72     5.16    14.89    19.36     6.13   
4804      0   210.50   162.72   148.73   144.62   150.96    70.64    55.06   
4805      0  1373.12  1460.25  1543.87  1585.65  1689.44  1775.72  1845.50   
4806      0    30.01    42.47    25.59    27.33    38.41    26.70    24.14   
4807      0  -591.74  -571.56  -580.32  -522.65  -496.57  -293.84   -95.74   

       FLUX.8   FLUX.9  ...  FLUX.3188  FLUX.3189  FLUX.3190  FLUX.3191  \
0      175.02   175.70  ...     131.66     143.17     190.08     138.63   
1        8.70    11.14  ...       7.54       7.43      -2.09      14.06   
2       -2.18    -3.13  ...      18.89      18.15      20.51      13.78   
3       27.00   -65.00  ...      57.00      41.69      75.75      99.63   
4     -153.78  -211.56  ...    1015.00    1054.44     975.03    1009.53   
...       ...      ...  ...        ...        ...        ...        ...   
4803    19.24     3.45  ...      -9.28      37.19      35.75      63.11   
4804    70.12    67.70  ...     -21.68     -78.74    -142.32    -176.99   
4805  1952.56  2052.97  ...    -656.03    -607.41    -476.91    -375.69   
4806    16.66    23.63  ...      24.51      34.49      24.45      14.93   
4807  -430.12  -466.17  ...      60.95      21.38      28.43      -3.49   

      FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0        148.90     151.77      83.11      84.24     105.44     117.55  
1          3.41      12.41     -12.72       4.81      -2.87       2.59  
2         20.28      20.91      -7.91      -1.59      -2.48      -3.20  
3         59.88      71.57      -0.69      86.07     171.57      75.00  
4       1016.22    1065.31    1014.09    1022.56    1043.37    1075.69  
...         ...        ...        ...        ...        ...        ...  
4803      30.55      42.53      63.00      90.28      64.55      74.83  
4804    -224.43    -282.02    -315.21    -308.97    -238.11    -188.83  
4805    -274.31     -99.66   -2032.16   -1924.44   -1874.25   -1796.19  
4806      10.78      25.11       9.15      29.58      27.07      19.05  
4807     -20.14     -50.59     -69.67     -53.18     -69.59     -53.81  

[4808 rows x 3198 columns]

In [5]:
print(f"""Maximo:\t{df_train[df_train.columns[1:]].values.max():.2f}
Minimo:\t{df_train[df_train.columns[1:]].values.min():.2f}
Media:\t{df_train[df_train.columns[1:]].values.mean():.2f}
Desviacion estandar: {df_train[df_train.columns[1:]].values.std():.2f}""")

Maximo:	4299288.00
Minimo:	-2385019.12
Media:	126.86
Desviacion estandar: 21826.89


In [6]:
X = df_train.drop(columns=["LABEL"])
y = df_train["LABEL"]

In [7]:
y.value_counts()

0    4775
1      33
Name: LABEL, dtype: int64

In [8]:
print("Before OverSampling, counts of label '1': {}".format(sum(y == 1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y == 0)))

sm = SMOTE(random_state = 22)
X_res, y_res = sm.fit_resample(X, y.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_res == 1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_res == 0)))

Before OverSampling, counts of label '1': 33
Before OverSampling, counts of label '0': 4775 

After OverSampling, the shape of train_X: (9550, 3197)
After OverSampling, the shape of train_y: (9550,) 

After OverSampling, counts of label '1': 4775
After OverSampling, counts of label '0': 4775


In [9]:
stdescaler = StandardScaler()
X_scaled = stdescaler.fit_transform(X_res)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_res, test_size=0.24, random_state=2)

In [11]:
dict(zip(*np.unique(y_train, return_counts=True)))

{0: 3579, 1: 3679}

In [23]:
Rforest = RandomForestClassifier(n_estimators=200, n_jobs=-1)
Rforest.fit(X_train, y_train.ravel())
predictions = Rforest.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1196
           1       1.00      1.00      1.00      1096

    accuracy                           1.00      2292
   macro avg       1.00      1.00      1.00      2292
weighted avg       1.00      1.00      1.00      2292



In [24]:
print(confusion_matrix(y_test, predictions))

[[1195    1]
 [   0 1096]]


In [22]:
rfc = DecisionTreeClassifier()
rfc.fit(X_train, y_train.ravel())
predictions = rfc.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97      1196
           1       0.95      0.99      0.97      1096

    accuracy                           0.97      2292
   macro avg       0.97      0.97      0.97      2292
weighted avg       0.97      0.97      0.97      2292



In [15]:
xgbCl = xgboost.XGBClassifier()
xgbCl.fit(X_train, y_train.ravel())
predictions = xgbCl.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1196
           1       1.00      1.00      1.00      1096

    accuracy                           1.00      2292
   macro avg       1.00      1.00      1.00      2292
weighted avg       1.00      1.00      1.00      2292



In [16]:
print(confusion_matrix(y_test, predictions))

[[1194    2]
 [   0 1096]]


In [17]:
xgbCl.save_model("model_xgb.json")

### Preprocess for test data

In [19]:
df_test = pd.read_csv('test.csv')
df_test

FLUX.1  FLUX.2  FLUX.3  FLUX.4  FLUX.5   FLUX.6   FLUX.7   FLUX.8  \
0   -171.30 -151.16 -157.96 -167.62 -145.93  -152.78  -153.02  -155.43   
1   -504.50 -643.06 -766.56 -899.12 -965.12 -1080.19 -1137.62 -1165.62   
2   -224.44 -195.62 -206.94 -329.56 -385.75  -375.94  -455.38  -532.88   
3    159.66  138.18  161.63  149.70  161.82   127.68   157.76    75.66   
4     67.38   69.51   62.63   47.53   48.44    43.56    41.43    43.44   
..      ...     ...     ...     ...     ...      ...      ...      ...   
844  332.44  287.86  313.24  290.21  271.03   286.99   245.03   248.51   
845   -0.42   -1.14    2.25   -3.49    4.88     8.43     9.35     2.80   
846 -131.10  -91.11  -72.02  -85.96  -73.96   -56.25   -48.71   -55.38   
847  323.51  285.75  283.15  237.64  208.31   142.98    78.37    73.03   
848  -11.29   -9.80   -7.80   26.18   -3.48     6.60     5.41    16.48   

      FLUX.9  FLUX.10  ...  FLUX.3188  FLUX.3189  FLUX.3190  FLUX.3191  \
0    -155.21  -152.89  ...     -18.11     -17.65     -18.31     -18.73   
1   -1240.62 -1167.25  ...     302.12     351.38     442.25     394.56   
2    -508.69  -586.06  ...     132.75     134.00     138.88     220.88   
3      56.18    77.11  ...      64.76      41.37      43.23       1.95   
4      41.44    37.09  ...       1.97      -3.42       5.12       2.92   
..       ...      ...  ...        ...        ...        ...        ...   
844   252.49   213.02  ...     -16.41     -16.35       1.80      -3.46   
845     1.90     2.95  ...       5.42       3.05       7.65      11.01   
846   -44.19   -62.16  ...     -37.28       8.93     -14.82      41.53   
847    50.20    23.95  ...     -93.96     -99.42     -32.63     -80.77   
848    14.82    15.49  ...       4.80      12.01      17.04      14.95   

     FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0         2.25       6.13     -49.52     -32.39     -22.50     -24.50  
1       545.88     625.00     113.88      81.38      31.69     156.06  
2       136.25     195.62    -145.12       5.44      90.75     121.81  
3         5.24      -2.81       5.31      -7.05       2.67      18.25  
4         4.48      -5.96      16.97      13.36      15.53       7.70  
..         ...        ...        ...        ...        ...        ...  
844     -21.26     -83.02      82.24      18.73      29.32      11.98  
845      10.72      -4.03       6.65       2.37       4.96      12.13  
846      64.06      35.11     -35.44     -38.50      14.67      -1.21  
847     -29.91     -55.91    -139.32    -130.96    -101.02     -85.14  
848      18.06      19.97      -5.75      -7.51      -9.21     -15.96  

[849 rows x 3197 columns]

In [20]:
X_test_scaled = stdescaler.transform(df_test)

In [27]:
predicciones_datathon_rforest = Rforest.predict(X_test_scaled)
predicciones_datathon_rforest

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [29]:
dict(zip(*np.unique(predicciones_datathon_rforest, return_counts=True)))

{0: 849}

In [30]:
predicciones_datathon_xgb = xgbCl.predict(X_test_scaled)
predicciones_datathon_xgb

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [31]:
dict(zip(*np.unique(predicciones_datathon_xgb, return_counts=True)))

{0: 847, 1: 2}

In [33]:
df_resultado = pd.DataFrame(predicciones_datathon_xgb, columns=["LABEL"], dtype="int16")
df_resultado

LABEL
0        0
1        0
2        0
3        0
4        0
..     ...
844      0
845      0
846      0
847      0
848      0

[849 rows x 1 columns]

In [36]:
df_resultado[df_resultado["LABEL"]==1]

LABEL
299      1
460      1

In [38]:
df_resultado.to_csv("prediccion.csv", index=False)

In [14]:
classifiers = []

xgbClassifier = xgboost.XGBClassifier()
classifiers.append(xgbClassifier)

svc = svm.SVC()
classifiers.append(svc)

dtc = tree.DecisionTreeClassifier()
classifiers.append(dtc)

rfc = RandomForestClassifier()
classifiers.append(rfc)

In [15]:
for clf in classifiers:
    clf.fit(X_train, y_train)
    y_pred= clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy of %s is %s\n" % (clf, acc))
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix of %s is %s\n\n" % (clf, cm))

Accuracy of XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0, ...) is 0.9991273996509599

Confusion Matrix of XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metri